SET IDENTITY_INSERT [dbo].[Employees] ON
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (1, N'Diana', N'Hamlick', N'1963-07-22', N'Human Resources')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (2, N'Bezalel', N'Simmel', N'1964-06-02', N'Management')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (3, N'Parto', N'Bamford', N'1959-12-03', N'Advertising')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (4, N'Chirstian', N'Koblick', N'1954-05-01', N'Sales')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (5, N'Kyoichi', N'Maliniak', N'1955-01-21', N'Accoutancy')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (6, N'Anneke', N'Preusig', N'1953-04-20', N'Purchases')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (7, N'Tzvetan', N'Zielinski', N'1957-05-23', N'Marketing')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (8, N'Saniya', N'Kalloufi', N'1958-02-19', N'Security')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (9, N'Sumant', N'Peac', N'1952-04-19', N'Testing')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (10, N'Duangkaew', N'Piveteau', N'1963-06-01', N'Logistics')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (11, N'Mary', N'Sluis', N'1953-11-07', N'Administration')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (12, N'Patricio', N'Bridgland', N'1960-10-04', N'Research')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (13, N'Eberhardt', N'Terkki', N'1963-06-07', N'Sales')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (14, N'Berni', N'Genin', N'1956-02-12', N'Customer service')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (15, N'Guoxiang', N'Nooteboom', N'1959-08-19', N'Human Resources')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (16, N'Kazuhito', N'Cappelletti', N'1961-05-02', N'Legal')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (17, N'Christine', N'Bouloucos', N'1958-07-06', N'Developement')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (18, N'Kazuhide', N'Peha', N'1954-06-19', N'Shipping')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (19, N'Lillian', N'Haddadi', N'1953-01-23', N'Logistics')
INSERT INTO [dbo].[Employees] ([ID], [FirstName], [LastName], [BirthDate], [Department]) VALUES (20, N'Mayuko', N'Warwick', N'1952-12-24', N'IT')
SET IDENTITY_INSERT [dbo].[Employees] OFF
